### ISSUE TITLE
Error installing on MacOS X

### ISSUE THREAD

**Issue by philpraxis** [pinax/pinax-utils#1]
```
$ pip install --extra-index-url=http://dist.pinaxproject.com/dev/  pinax-utils==1.0b1.dev3
Downloading/unpacking pinax-utils==1.0b1.dev3
  http://dist.pinaxproject.com/dev/pinax-utils/ uses an insecure transport scheme (http). Consider using https if dist.pinaxproject.com has it available
  Downloading pinax-utils-1.0b1.dev3.tar.gz
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/private/tmp/test1/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/private/tmp/test1/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/private/tmp/test1/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/private/tmp/test1/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/private/tmp/test1/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/private/tmp/test1/lib/python2.7/site-packages/pip/util.py", line 625, in unpack_file
    untar_file(filename, location)
  File "/private/tmp/test1/lib/python2.7/site-packages/pip/util.py", line 543, in untar_file
    tar = tarfile.open(filename, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1678, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1727, in gzopen
    **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1705, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 1574, in __init__
    self.firstmember = self.next()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tarfile.py", line 2331, in next
    raise ReadError(str(e))
ReadError: invalid header

Storing debug log for failure in /Users/user/.pip/pip.log
```

on MacOS X Mavericks:
$ uname -a
Darwin mb 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64
$

Looks like a tar file has an invalid header.

**Comment by KatherineMichel** [comment]
Hi @philpraxis. Sorry for the very late reply. In the interest of closing the issue, when I ran ```pip install http://dist.pinaxproject.com/dev/pinax-utils/pinax-utils-1.0b1.dev3.tar.gz``` the app was installed in the site-packages directory of the project's virtualenv. Not sure what the header issue was all about. Presumably, it's irrelevant now...? Let me know if any other questions.
